### PR TITLE
problem with wiki_policy_spec

### PR DESCRIPTION
**Pull request by praveenyr**
**Description** : The wiki policy spec seems to error out , with the way I assign the user for the wiki. Didn't want to spend too much time on it.
Seed data is all set.

**Coverage**: 81.51%

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@praveenyr I will review tonight! Thanks for the PR.

**Comment by brittanyjspringer** [comment]
@praveenyr back to you! 

I just pushed a commit with the following: 

* working WikiPolicy spec
* Factories for User, Wiki 
* Modified show permission for Wikis (all users should see these)
* Simplecov coverage added to .gitignore 

Now it is your turn: 

* Please pull this branch down and review the Policy spec and make sure it makes sense
* Run the app and make sure that you can view Wikis created by other users
* Fix the WikiController tests, ideally switching to use FactoryGirl like I did in the WikiPolicy test 

Please let me know if you need more help. I'll be busy Saturday but can definitely help Sunday.

**Comment by praveenyr** [comment]
@wonderwoman13 The tests look good,thanks.Sorry,the tests' format in the pundit-matcher docs looked a little different.

I also tested the app,made a small change to seed data to confirm the admin user and checked it in.

**Comment by brittanyjspringer** [comment]
@praveenyr excellent! Are all of your tests passing now?

**Comment by brittanyjspringer** [comment]
I'm going to close this PR and will let you open a new one to submit.

**Comment by praveenyr** [comment]
Yes,all the test are passing now @wonderwoman13 .

**Pull request closed without merging**
